---
- name: Prepare
  hosts: all
  tasks:
    - name: full system upgrade
      become: true
      community.general.pacman:
        update_cache: true
        upgrade: true
      when:
        - ansible_distribution == "Archlinux"
